[project]
name = "eli-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=0.37.1",
    "langchain-core>=1.2.0",
    "langchain-groq>=1.1.1",
    "python-dotenv>=1.2.1",
    "streamlit>=1.52.1",
]
